FROM python:3.9-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN mkdir -p /usr/app/backend/
WORKDIR /usr/app/backend/

COPY . /usr/app/backend/

RUN pip install --no-cache-dir -r requirements.txt
