# Generated by Django 4.1.2 on 2023-02-03 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.product', verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.color', verbose_name='Цвет товара'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.size', verbose_name='Размер товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.color', verbose_name='Цвет по умолчанию'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='product_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='material',
            name='products',
            field=models.ManyToManyField(related_name='materials', through='product.MaterialProduct', to='product.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='image',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(to='product.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_categories', to='product.category', verbose_name='Родительская категория'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (0, 10))), name='product_review_rating_between_0_and_10'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productdetails',
            unique_together={('product', 'product_color', 'product_size')},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('discount__range', (0, 99))), name='product_product_discount_between_0_and_99'),
        ),
        migrations.AddConstraint(
            model_name='materialproduct',
            constraint=models.CheckConstraint(check=models.Q(('part__range', (1, 100))), name='product_materialproduct_part_between_1_and_100'),
        ),
        migrations.AlterUniqueTogether(
            name='materialproduct',
            unique_together={('product_material', 'product')},
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount__range', (0, 99))), name='product_coupon_discount_between_0_and_99'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('use_limit__isnull', True), ('use_limit__gt', 0), _connector='OR'), name='product_coupon_use_limit_is_null_or_greater_then_0'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('used_amount__gte', 0)), name='product_coupon_used_amount_greater_then_0_or_equal'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('use_limit__isnull', True), ('use_limit__gte', models.F('used_amount')), _connector='OR'), name='product_coupon_used_amount_less_then_use_limit_or_equal'),
        ),
    ]
