# Generated by Django 4.1 on 2022-08-22 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'get_latest_by': '-created_at', 'ordering': ['-is_valid', '-valid_until'], 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterModelOptions(
            name='deliverer',
            options={'get_latest_by': '-created_at', 'ordering': ['delivery_price'], 'verbose_name': 'Доставщик', 'verbose_name_plural': 'Доставщики'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'get_latest_by': '-created_at', 'ordering': ['name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': '-created_at', 'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'get_latest_by': '-created_at', 'ordering': ['-order'], 'verbose_name': 'Детали заказа', 'verbose_name_plural': 'Детали заказов'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'get_latest_by': '-created_at', 'ordering': ['-created_at'], 'verbose_name': 'Точка', 'verbose_name_plural': 'Точки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['color_hex'], 'verbose_name': 'Цвет товара', 'verbose_name_plural': 'Цвета товаров'},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={'get_latest_by': '-created_at', 'ordering': ['-product'], 'verbose_name': 'Детали товара', 'verbose_name_plural': 'Детали товаров'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'get_latest_by': '-created_at', 'ordering': ['-product'], 'verbose_name': 'Фотография продукта', 'verbose_name_plural': 'Фотографии продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'ordering': ['name'], 'verbose_name': 'Материал продукта', 'verbose_name_plural': 'Материалы продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['size'], 'verbose_name': 'Размер товара', 'verbose_name_plural': 'Размеры товаров'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'get_latest_by': '-created_at', 'ordering': ['-product'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(to='api.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='use_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лимит использований'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_amount',
            field=models.IntegerField(default=0, verbose_name='Количество использований'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='delivery_price',
            field=models.IntegerField(verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deliverer', verbose_name='Доставщик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.point', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productdetails', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='unit_price',
            field=models.IntegerField(verbose_name='Цена за штуку'),
        ),
        migrations.AlterField(
            model_name='point',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='point',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='point',
            name='location',
            field=models.CharField(max_length=40, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='point',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='point',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.productcolor', verbose_name='Цвет по умолчанию'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_hex',
            field=models.CharField(max_length=7, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.productcolor', verbose_name='Цвет товара'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.productsize', verbose_name='Размер товара'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='stored',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.productcolor', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='products',
            field=models.ManyToManyField(through='api.productmaterial_product', to='api.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=3, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together={('order', 'product_details')},
        ),
        migrations.AlterUniqueTogether(
            name='productdetails',
            unique_together={('product', 'product_color', 'product_size')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount__range', (0, 99))), name='api_coupon_discount_between_0_and_99'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('use_limit__isnull', True), ('use_limit__gt', 0), _connector='OR'), name='api_coupon_use_limit_is_null_or_greater_then_0'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('used_amount__gte', 0)), name='api_coupon_used_amount_greater_then_0_or_equal'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('delivery_price__gte', 0)), name='api_order_delivery_price_greater_then_0_or_equal'),
        ),
        migrations.AddConstraint(
            model_name='orderdetails',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gt', 0)), name='api_orderdetails_unit_price_greater_then_0'),
        ),
        migrations.AddConstraint(
            model_name='orderdetails',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='api_orderdetails_quantity_greater_then_0'),
        ),
        migrations.AddConstraint(
            model_name='orderdetails',
            constraint=models.CheckConstraint(check=models.Q(('discount__range', (0, 99))), name='api_orderdetails_discount_between_0_and_99'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('discount__range', (0, 99))), name='api_product_discount_between_0_and_99'),
        ),
        migrations.AddConstraint(
            model_name='productmaterial_product',
            constraint=models.CheckConstraint(check=models.Q(('part__range', (1, 100))), name='api_productmaterial_product_part_between_1_and_100'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (0, 10))), name='api_review_rating_between_0_and_10'),
        ),
    ]
