# Generated by Django 4.1.2 on 2023-02-03 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.useraddress', verbose_name='Адрес доставки'),
        ),
        migrations.AddConstraint(
            model_name='orderdetails',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gt', 0)), name='order_orderdetails_unit_price_greater_then_0'),
        ),
        migrations.AddConstraint(
            model_name='orderdetails',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='order_orderdetails_quantity_greater_then_0'),
        ),
        migrations.AddConstraint(
            model_name='orderdetails',
            constraint=models.CheckConstraint(check=models.Q(('discount__range', (0, 99))), name='order_orderdetails_discount_between_0_and_99'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together={('order', 'product_details')},
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('deliverer__isnull', False), ('point__isnull', True), ('user_address__isnull', False)), models.Q(('deliverer__isnull', True), ('point__isnull', False), ('user_address__isnull', True)), _connector='OR'), name='order_order_deliverer_and_address_or_point'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('delivery_price__gte', 0)), name='order_order_delivery_price_greater_then_0_or_equal'),
        ),
    ]
